apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: tekton-pvc-cleanup
  name: tekton-pvc-cleanup
  namespace: tekton-pipelines
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: ceph
