apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pr-cli-webhook
  labels:
    app.kubernetes.io/version: "1.0.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pr-cli
      app.kubernetes.io/component: webhook-service
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    scheme: http

