apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pr-cli-webhook
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pr-cli
      app.kubernetes.io/component: webhook-service

