# @jiraBaseUrl =
@issueIdOrKey =
# @jiraUsername =
# @jiraPassword =
# @jiraProject =

GET {{jiraBaseUrl}}/rest/api/2/issue/{{issueIdOrKey}}?fields=*all
Authorization: Basic {{jiraUsername}}:{{jiraPassword}}
Accept: application/json


###

GET {{jiraBaseUrl}}/rest/api/latest/user/assignable/search?username=&projectKeys={{jiraProject}}&issueKey={{issueIdOrKey}}
Authorization: Basic {{jiraUsername}}:{{jiraPassword}}

###


GET {{jiraBaseUrl}}/rest/api/latest/field
Authorization: Basic {{jiraUsername}}:{{jiraPassword}}
###

GET {{jiraBaseUrl}}/rest/api/latest/field/customfield_12242/contexts
Authorization: Basic {{jiraUsername}}:{{jiraPassword}}

###


GET {{jiraBaseUrl}}/rest/api/latest/customField/customfield_12242/option
Authorization: Basic {{jiraUsername}}:{{jiraPassword}}

###


### Project details


GET {{jiraBaseUrl}}/rest/api/2/project/{{jiraProject}}
Authorization: Basic {{jiraUsername}}:{{jiraPassword}}
